- .gitlab-ci.yml
> Fixed manual deploy for master branch

- src/main.rs
logout зарегестрирован в списке маршрутов
> Logout registered in routes list

- frontend/src/components/Modal.vue
- frontend/src/components/TopBarContextMenu.vue
- frontend/src/variables.sass
Added new media for small screens (less than 600px)
*Bonus: margin and border radius added for authorization modal on mobile devices
#31
> Mobile version of context menu for authorized user

- .gitlab-ci.yml
> Fixed migrations for new structure

- .gitlab-ci.yml
> Fixed wrong command order

- .gitlab-ci.yml
> Fixed dir for rest of commands

- backend/src/tests.rs
> Fixed tests for new dir structure

- .idea/blog.iml
- .idea/inspectionProfiles/profiles_settings.xml
- frontend/.idea/frontend.iml
- frontend/.idea/inspectionProfiles/Project_Default.xml
- frontend/.idea/inspectionProfiles/profiles_settings.xml
- frontend/.idea/misc.xml
- frontend/.idea/modules.xml
- frontend/.idea/vcs.xml
- frontend/src/components/Modal.vue
- frontend/src/components/ModalAuthorization.vue
- frontend/src/components/ModalAuthorizationLogin.vue
- frontend/src/components/TopBarContextMenu.vue
- frontend/src/storage_modules/Authorization.js
Added state of authorization loading to storage
#34
> State of loading

- frontend/src/components/ModalAuthorizationRegistration.vue
Added registration prototype
#7
> Registration added

- .gitlab-ci.yml
> Fixed repository name

- frontend/src/App.vue
- frontend/src/components/ArticleList.vue
- frontend/src/components/ArticleListItem.vue
- frontend/src/components/ComponentLoading.vue
- frontend/src/components/Modal.vue
- frontend/src/components/ModalAuthorizationLogin.vue
- frontend/src/components/ModalAuthorizationRegistration.vue
- frontend/src/components/TopBar.vue
- frontend/src/components/TopBarContextMenu.vue
- frontend/src/router.js
- frontend/src/storage_modules/Authorization.js
- frontend/src/variables.sass
> Now articles list loads from server

- backend/src/posts_view.rs
> Fixed routes ranking for get_post

- backend/src/main.rs
- backend/src/user.rs
- backend/src/users_view.rs
> Removed unused imports

- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/ComponentLoading.vue
- frontend/src/components/ModalAuthorizationLogin.vue
- frontend/src/components/TopBar.vue
- frontend/src/components/TopBarContextMenu.vue
- frontend/src/storage_modules/Authorization.js
- frontend/src/variables.sass
> Feature blog 56

- frontend/src/components/TopBarContextMenu.vue
- frontend/src/storage_modules/Authorization.js
> Logout now is a storage action

- frontend/src/App.vue
- frontend/src/components/ModalAuthorizationLogin.vue
- frontend/src/components/TopBarContextMenu.vue
- frontend/src/storage_modules/Authorization.js
> Now promise processed in component

- backend/src/users_view.rs
> Removed token guard from get users route #63

- frontend/src/components/ArticleListItem.vue
> Now images little bit bigger and displayed on mobile devices

- backend/src/posts_view.rs
> Задача #30: Условное получение списка публикаций

- backend/src/main.rs
- backend/src/posts_view.rs
> Задача #81: Исправлен баг при получении публикации по id

- .idea/runConfigurations/blog.xml
- .idea/runConfigurations/web.xml
> Задача #83: Добавлены конфигурации запуска для папки проекта

- frontend/src/components/ArticleComponent.vue
- frontend/src/components/ArticleListItem.vue
- frontend/src/components/LazyImage.vue
> Prototype of lazy image component with padding prop

- backend/src/users_view.rs
> Added token deletion from cookie in delete user method #68

- frontend/src/components/Modal.vue
- frontend/src/components/ModalAuthorizationLogin.vue
- frontend/src/components/ModalAuthorizationRegistration.vue
- frontend/src/storage_modules/Authorization.js
Registration in store, login button unlocks only when all input filled
#65
> Now registration in storage

- frontend/src/App.vue
- frontend/src/components/ArticleComponent.vue
- frontend/src/variables.sass
> Changed font and article size, now scroll displayed in all pages

- frontend/src/components/LazyImage.vue
> Now only high res images have delay to load

- frontend/src/components/TopBarContextMenu.vue
- frontend/src/components/UserPublications.vue
- frontend/src/router.js
> Fixed components name

- backend/src/users_view.rs
> Creating session on registration added #64

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- frontend/package-lock.json
- frontend/package.json
> Обновить уязвимый ESLint

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- frontend/.idea/codeStyles/codeStyleConfig.xml
- frontend/package.json
- frontend/src/App.vue
- frontend/src/api.js
- frontend/src/article_style.sass
- frontend/src/components/ArticleComponent.vue
- frontend/src/components/ArticleFeed.vue
- frontend/src/components/ArticleList.vue
- frontend/src/components/LazyImage.vue
- frontend/src/components/Modal.vue
- frontend/src/components/ModalAuthorization.vue
- frontend/src/components/ModalAuthorizationLogin.vue
- frontend/src/components/ModalAuthorizationRegistration.vue
- frontend/src/components/TopBar.vue
- frontend/src/components/TopBarContextMenu.vue
- frontend/src/components/UserPublications.vue
- frontend/src/components/editor/ArticleEditorTextEditor.vue
- frontend/src/components/editor/ArticlesEditor.vue
- frontend/src/directives.js
- frontend/src/main.js
- frontend/src/router.js
- frontend/src/server_defaults.js
- frontend/src/storage.js
- frontend/src/storage_modules/Authorization.js
- frontend/src/storage_modules/ModalShown.js
Я снова не понимаю что я сломал и почему он не может автоматически смерджиться, простите Христа ради.
> Feature blog 108

- frontend/src/components/editor/ArticleEditorTextEditor.vue
В этот раз пулл реквест куда надо
Карточка всё так же заезжает под поле в редакторе
> md editor inserted to module

- frontend/src/api.js
- frontend/src/components/editor/ArticleEditorTextEditor.vue
- frontend/src/components/editor/ArticlesEditor.vue
> Feature blog 163 

- README.md
> Switch CircleCI badge to dev branch
